### ISSUE TITLE
Additional files to edit when using the template

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-plugin-starter-template#131]
In addition to editing plugin.json, it seems there are other files that might need to be updated with the new plugin ID?
- .golangci.yml:
```yml
linters-settings:
  // [...]
  goimports:
    local-prefixes: github.com/mattermost/mattermost-starter-template
```

- go.mod
```go
module github.com/mattermost/mattermost-plugin-starter-template
```
